name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Tá»± Ä‘á»™ng cháº¡y khi báº¡n sá»­a báº¥t ká»³ file nÃ o trong folder backend

jobs:
  deploy-be:
    name: ğŸš€ Deploy Backend to InfinityFree
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Sync Backend files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_40701573
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /htdocs/backend/ # Dáº¥u / á»Ÿ Ä‘áº§u cá»±c ká»³ quan trá»ng Ä‘á»ƒ Ä‘á»‹nh vá»‹ Ä‘Ãºng htdocs