name: Deploy Backend
on:
  push:
    paths:
      - 'backend/**' # Chá»‰ cháº¡y khi cÃ³ thay Ä‘á»•i trong thÆ° má»¥c backend
jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ðŸ“‚ Sync Backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_40701573
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: htdocs/backend/