name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Chá»‰ cháº¡y khi cÃ³ thay Ä‘á»•i trong thÆ° má»¥c backend

jobs:
  deploy-be:
    name: ðŸš€ Deploy Backend to InfinityFree
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Sync Backend files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_40701573
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: htdocs/backend/ 