name: Deploy Frontend
on:
  push:
    paths:
      - 'frontend/**' # Chá»‰ cháº¡y khi cÃ³ thay Ä‘á»•i trong thÆ° má»¥c frontend
jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ðŸ“‚ Sync Frontend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_40701573
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: htdocs/frontend/