name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Tá»± Ä‘á»™ng cháº¡y khi báº¡n sá»­a file trong folder frontend

jobs:
  deploy-fe:
    name: ğŸ¨ Deploy Frontend to InfinityFree
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Sync Frontend files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_40701573
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: /htdocs/ # Äáº£m báº£o file index.html náº±m Ä‘Ãºng htdocs/frontend/